### ISSUE TITLE
Update crate link and fix the release action

### ISSUE THREAD

**Issue by dilawar** [SubconsciousCompute/SimpleAccumulator#2]

**Comment by sn99** [comment]
@dilawar Can you make a crates.io account for yourself? I think it is best that I add you as owner there too.

![image](https://user-images.githubusercontent.com/42946112/181613570-c3aa9b63-f3ec-48ff-b7eb-7225a53d644f.png)

**Comment by dilawar** [comment]
![image](https://user-images.githubusercontent.com/895681/181670572-8681b3b3-c2ce-4eb7-a45c-0c936aa14fd7.png)

**Comment by dilawar** [comment]
Thanks. Version 0.3.2 is published now.
