### ISSUE TITLE
Support `append` method 

### ISSUE THREAD

**Issue by dilawar** [SubconsciousCompute/SimpleAccumulator#3]
Currently, only `push` is supported that takes one value and add to the accumulator. Support `append` that can take a vector of values like https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append.

**Comment by sn99** [comment]
@dilawar What kind of behavior do you want when capacity if fixed? Do you want it to grow to a new capacity or rewrite previous values aka instead of `append` we actually `replace`?

**Comment by dilawar** [comment]
The behavior of the fixed capacity accumulator should be just like CircularBuffer (https://en.wikipedia.org/wiki/Circular_buffer).
